### ISSUE TITLE
Coordinate and finish the service card 

### ISSUE THREAD

**Issue by Hayaco** [Raouf16/teach_spreadsheets#13]
We also have to add some attributes that we need for the service card in the teacher object, and in the csv file (civility and discipline).

**Comment by Hayaco** [comment]
The code is in the package com.github.Raouf16.model.createFile, class SpreadSheetFill.
We enconter a problem : outOfBoundException but we didn't succed to resolve it so Raouf will try to repair the bug.

**Comment by Raouf16** [comment]
I had to change all the function because of several missings .. the function is now devided on 2 methods, one to create an Empty Fiche de service (Without personal informations) and a method to create a Full Fiche de service (With personal informations), managed with exceptions because of Files & I added a converter to PDF at the end.
